In [63]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [115]:
df = pd.DataFrame({
    'age': [25, np.nan, 35, 40],
    'salary': [50000, 60000, np.nan, 80000]
})

# Missing Values

In [116]:
df['age'] = df['age'].fillna(df['age'].mean())

In [117]:
df['salary'] = df['salary'].fillna(df['salary'].median())

In [118]:
df

         age   salary
0  25.000000  50000.0
1  33.333333  60000.0
2  35.000000  60000.0
3  40.000000  80000.0

In [119]:
imp = SimpleImputer(strategy='mean')
cleaned = imp.fit_transform(df)

In [120]:
cleaned

array([[2.50000000e+01, 5.00000000e+04],
       [3.33333333e+01, 6.00000000e+04],
       [3.50000000e+01, 6.00000000e+04],
       [4.00000000e+01, 8.00000000e+04]])

# Remove Duplicates

In [121]:
df2 = pd.DataFrame({'age': [40],'salary': [80000]})
df = pd.concat([df,df2], ignore_index=True)
df

         age   salary
0  25.000000  50000.0
1  33.333333  60000.0
2  35.000000  60000.0
3  40.000000  80000.0
4  40.000000  80000.0

In [122]:
df = df.drop_duplicates()
df['age'] = df['age'].astype('int')

C:\Users\Admin\AppData\Local\Temp\ipykernel_18756\3867602089.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].astype('int')

In [123]:
df

   age   salary
0   25  50000.0
1   33  60000.0
2   35  60000.0
3   40  80000.0

# Encoding Categorical Variables

In [124]:
df1 = pd.DataFrame({
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Chennai']
})
df_encoded = pd.get_dummies(df1, columns=['city'])
df_encoded

   city_Chennai  city_Delhi  city_Mumbai
0         False        True        False
1         False       False         True
2         False        True        False
3          True       False        False

# Scaling Numerical Features

In [126]:
scaler = StandardScaler()
scaled = scaler.fit_transform(df[['age', 'salary']])
scaled

array([[-1.52705788, -1.14707867],
       [-0.04627448, -0.22941573],
       [ 0.32392137, -0.22941573],
       [ 1.249411  ,  1.60591014]])

# Group BY

In [127]:
data = {
    'Region': ['East', 'West', 'East', 'North', 'West'],
    'Sales': [200, 150, 300, 100, 220],
    'Profit': [20, 15, 30, 10, 25]
}
df = pd.DataFrame(data)
df_group = df.groupby('Region')['Sales'].sum()
print(df_group)

Region
East     500
North    100
West     370
Name: Sales, dtype: int64

# Pivot Table

In [128]:
data = {
    'Region': ['East','East','West','West','North'],
    'Product': ['A','B','A','B','A'],
    'Sales': [200, 250, 300, 100, 120]
}
df = pd.DataFrame(data)
pivot = pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='sum')
print(pivot)

Product      A      B
Region
East     200.0  250.0
North    120.0    NaN
West     300.0  100.0